name: Go

on:
  release:
    types:
      - created

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.x
    - name: Build
      run: go build -v -o artifacts/bin/ ./... 
    - uses: actions/upload-artifact@v3
      with:
        name: aptly-mirror
        path: artifacts/bin/aptly-mirror
